<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Administrador extends Model
{
    protected $table = 'administrador'; // matches your table name
    protected $primaryKey = 'id_administrador';
    public $timestamps = true;

    protected $fillable = [
        'id_usuario',
    ];

    // Relation to User
    public function user(): BelongsTo
    {
        return $this->belongsTo(User::class, 'id_usuario');
    }

    // Relation: reports generated by admin
    public function reportes(): HasMany
    {
        return $this->hasMany(Reporte::class, 'id_usuario_admin');
    }

    // Relation: notifications received
    public function notificaciones(): HasMany
    {
        return $this->hasMany(Notificacion::class, 'id_usuario_destino');
    }
}
